name: e2e
on: [push]
jobs:
  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: |
          brew tap wix/brew
          brew install applesimutils
          brew cask install thii/swift-runtime/swift-runtime
          brew install xcbeautify
          cd example
          npx appium-doctor
          yarn e2e:start-server --log-level info --default-capabilities '{ "newCommandTimeout":660 }' > appium_log.txt &
          echo installing yarn dependencies
          echo -----------------------------
          yarn
          echo installing pod dependencies
          ls
          echo -----------------------------
          yarn clean:ios
          set -o pipefail && yarn build:e2e:ios | xcbeautify
          yarn zip:build:ios
          e2e/run-e2e.js --platform=ios --platformVersion=14.4
          cat ./appium_log.txt
